version: '3.5'

services:
  mysql-server:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    restart: always
    depends_on:
      - mysql-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./zbx_server:/etc/zabbix
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    restart: always
    depends_on:
      - zabbix-server
      - mysql-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      PHP_TZ: ${PHP_TZ}
    ports:
      - "8080:8080"
      - "8443:8443"

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.0-latest
    restart: always
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
    volumes:
      - ./zbx_agent:/etc/zabbix
