
version: '3.5'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-server
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - zabbix-net
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4-latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ZBX_JAVAGATEWAY_ENABLE=${ZBX_JAVAGATEWAY_ENABLE}
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    depends_on:
      - postgres
    networks:
      - zabbix-net
    ports:
      - "10051:10051"
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4-latest
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - PHP_TZ=Asia/Ho_Chi_Minh
    depends_on:
      - postgres
      - zabbix-server
    networks:
      - zabbix-net
    ports:
      - "80:8080"
    restart: always

  zabbix-agent:
    image: zabbix/zabbix-agent2:ubuntu-6.4-latest
    container_name: zabbix-agent
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=zabbix-server
    networks:
      - zabbix-net
    restart: always

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:ubuntu-6.4-latest
    container_name: zabbix-java-gateway
    networks:
      - zabbix-net
    restart: always

networks:
  zabbix-net:
    driver: bridge

volumes:
  postgres-data: